#-------------------------------
# STATS
stats:
  rate: 225
  rate-sale: 185
  8h: 1295
  class: 895
  class-sale:
  hours: 600
  years: 3
  views: 15 # in millions

#-------------------------------
# Site Settings
title: Learn SAT Math
logo: #  -- this logo would be in place of "Learn SAT Math"
description: I'm an SAT Math tutor at the University of Virginia helping students improve their SAT scores efficiently and without frustration.
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.

#-------------------------------
# Navigation Settings
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - url: '/about/'
      title: 'About'
    - url: '/strategy/'
      title: 'Strategy'
    - url: '/classes/'
      title: 'Classes'
    - title: 'Videos'
      url: '/projects/'
    - url: '/contact/'
      title: 'Contact'

#-------------------------------
# Author Settings
author:
  author__name: Eric
  author__bio: I'm a UVA student, educational content creator, and SAT Math tutor, here to help you improve your SAT Math score as efficiently as possible.
  author__avatar: '/images/eric4.JPG'

social:
- {icon: "ion-logo-youtube", link: "https://www.youtube.com/channel/UCFi7uuVtKZQG1YuMVT9xWtA"}
# Example of adding a new link to the footer - {icon: "ion-logo-dribbble", link: "https://dribbble.com"}
# Other icons can be found at https://ionicons.com/v4/

#-------------------------------
# Testimonials Section
testimonial__title: What students say
testimonial__description: 

testimonial__items:
  - name: "Illa"
    designation: "Group Classes"
    designation2: "690 to 770"
    content: "I cannot recommend Eric's group classes enough! I was completely stuck and unsure how to improve my math score, struggling to identify what I was missing. <strong>Eric’s group classes changed everything—he covered everything I encountered on test day.</strong> His teaching goes beyond rote learning; he focuses on building a <strong>solid foundational understanding</strong> of the concepts and equips students with strategies to approach <strong>every problem confidently</strong>. He helped me raise my overall score from a 1450 to a 1530!"

  - name: "Yuna"
    designation: "770 in 8 hours"
    content: "<strong>Learning from Eric was the best decision I made before taking the SAT</strong>. Before I started learning from him, I felt discouraged because I couldn't see any improvements in my math score. I learned a lot of things from him that I wouldn't have been able to figure out if I just self-studied. <strong>He also put in a lot of time and effort into personalizing my experience</strong>, helping me to focus on the areas I needed to improve. In every tutoring session, he was patient and understanding, and <strong>I felt really comfortable asking questions and making mistakes</strong>. I would recommend Eric to anyone taking the SAT because he really cares about helping his students succeed and makes studying effective and enjoyable!"

  - name: "Wyatt"
    designation: "Group Classes"
    designation2: "630 to 740"
    content: "When Eric says the SAT math score is the quickest way you can improve your college admissions, <strong>he is not lying.</strong> Taking his December SAT group classes and doing no work outside of sessions improved my score by 100 points. If you are serious about improving your SAT score <strong>fast</strong> at a <strong>reasonable price</strong> compared to other SAT tutors, <strong>taking Eric’s SAT class is a no brainer.</strong>"

  - name: "Sam"
    designation: "Group Classes"
    designation2: "650 to 770"
    content: "Taking group classes with Eric helped boost my SAT score tremendously! His class materials were well-thought-out, original, and personalized. <strong>There was no pressure to answer problems correctly, and there was no judgment if a student made mistakes.</strong> He has an engaging personality, so <strong>while practicing math is one of my least favorite activities, I genuinely enjoyed each session.</strong> While taking the SAT, I encountered several math concepts that we had covered together. His explanations were clear and memorable and I was able to confidently answer the questions correctly! Overall, his classes helped me <strong>increase my SAT math score by 120 points, helping me receive a total score of 1560.</strong>"

  - name: "James"
    designation: "640 to 750 in 8 hours"
    content: "<strong>My score increased faster than I thought was possible</strong>. Eric understands the SAT math on a deep level and can solve any problem I give him. He taught me not just how to solve problems, but how to think about them. Talking through my work out loud was especially impactful. Not only did I get a 750, but I've become a much better problem solver after learning from Eric."

  - name: "Aaron"
    designation: "Group Classes"
    designation2: "650 to 790"
    content: "Eric really understands the SAT because he himself took it so he can teach you all the tips and tricks to solve the hard questions that the SAT throws at you. <strong>He makes it super easy to understand each concept.</strong> Also, he gives so many study materials and plans. My math score was maxed out at 650 before Eric's classes, but now I was able to get a 790. I highly recommend this course for anyone who is taking the SAT."

  - name: "Mujtaba"
    content: "Eric's method of teaching was <strong>perfect</strong> for a student like me. While I was already at a relatively high score when I signed on, I improved drastically with the things I was struggling in. Each hard concept with just a little bit of practice and explaining from him improved my score another 10-20 points. The practice is also great. <strong>The hard question sets are exactly what you need to get as close to the 800 as possible.</strong> You won't see questions harder than that on the real thing so the practice is identical to the test. I think it's a great idea to <strong>invest</strong> in Eric if you're looking for a high score."

  - name: "Aanya"
    designation2: "580 to 710 in 8 hours"
    content: "<strong>Eric's math tutoring has helped me more than any textbook I have used</strong>. I was struggling with the math section of the SAT, staying at the same score even with months of studying. However once I found Eric's tutoring, my score improved significantly. Eric not only helped me get to the right answer for a problem, but he also made sure that I understood the reasoning behind it in depth. This was very beneficial as previously other tutors, textbooks, and even College Boards explanations would give me the long, tedious way to solve a problem, which no one has time to do on the SAT. I would highly recommend Eric for anyone who needs help in SAT math."

  - name: "Zoé"
    designation: "Group Classes"
    designation2: "Scored 760"
    content: "Classes were fun and interactive and gave me tips and methods which helped me secure the score I was aiming for. <strong>Eric is patient and helpful and encouraged us to find the answer by ourselves.</strong> The course was well structured and provided ample practice and review material. "

  - name: "Viraat"
    designation2: "680 to 750 in 6 hours"
    content: "Under Eric's lessons, I <strong>efficiently</strong> learned the concepts needed to master the SAT math problems. Eric's method of teaching concepts helped you answer <strong>any question</strong> that falls under that topic. With <strong>just six lessons</strong>, I improved my score by 70 points. With Eric's resources, I could do many practice problems independently and use them to understand how the SAT asks questions and master topics I struggled with."

  - name: "Mukhammad"
    image: "/images/icon.png"
    designation: "630 to 730 in 8 hours"
    content: "Eric is such a great math tutor who has helped me with my SAT journey. He is very clear when explaining math concepts and makes sure you understand the material. <strong>He always asks if you have questions and has no judgment if you do</strong>. His lessons are so worth it and with his affordable rates and bundles, he makes it accessible to everyone. I am so grateful to have Eric tutor me and recommend him to anyone looking to improve on the math section of the SAT."

  - name: "Ryan"
    image: "/images/icon.png"
    designation: "530 to 600 in 3 hours"
    content: "The lessons were highly comprehensible. He also demonstrated various methods of solving problems to ensure a thorough understanding of the solution's rationale. <strong>After only three lessons, my actual SAT math score improved by 70 points</strong>."

  - name: "Julia"
    image: "/images/icon.png"
    designation: "SAT Math & Precalculus"
    content: "Eric is a great tutor who makes math enjoyable and bearable. <strong>He does a great job explaining concepts and ensuring I don't get lost along the way</strong>. I like and understand the unit circle for precalc now! I'm glad we found Eric as an SAT Math and Precalc tutor."

  - name: "Naoki"
    image: "/images/icon.png"
    designation2: "660 to 760 in 8 hours"
    content: "Since I found Eric online, <strong>it has been a life changing experience for me</strong>! He is very knowledgeable in the field of math, especially in Algebra and SAT Math, not only explaining how to solve problems, but also in depth reasoning behind the math. <strong>I was struggling with SAT math and feeling discouraged, but Eric's patient and encouraging approach helped me gain confidence</strong>. He will explain in detail any way possible for you to understand, plus provide helpful tips and tricks that make problem solving not only easier, but also faster. With his guidance and support, I was able to achieve my goal (SAT Math 750+). I HIGHLY RECOMMEND Eric as a math tutor to anyone in need of help in math."

#-------------------------------
# Blog Section
#blog__settings:
#  blog__title: Recent Posts
#  blog__description:

#-------------------------------
# Footer Navigation Settings
footer_menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - url: '/about/'
      title: 'About'
    - url: '/strategy/'
      title: 'Strategy'
    - url: '/classes/'
      title: 'Classes'
    - title: 'Videos'
      url: '/projects/'
    - url: '/contact/'
      title: 'Contact'
    #- url: '/subjects/'
    #  title: 'Subjects'

#-------------------------------
# Contact Settings
contact:
  email: mldrzyvr # Add your form_id
  description: # Add a description of your form

# NOTE
# Hilton theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: learnsatmath # Add your shortname for Disqus Comment. For example anvodstudio-demo

#-------------------------------
# Google Analytics
google-analytics: G-EKENVY91TK

#-------------------------------
# Newsletter
mailchimp: enable # To enable the mailchimp form, use the value 'enable'. To disable the form, leave the field blank.
mailchimp__identifier: frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3 # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
mailchimp__input__text: Your email address...
mailchimp__button__text: Get updates